# Generated by Django 2.2.4 on 2021-01-16 18:51

from django.db import migrations
import phonenumbers


def transfer_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owner_pure_phone = parsed_phone
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210116_2128'),
    ]

    operations = [migrations.RunPython(transfer_phone_numbers),
    ]
