# Generated by Django 2.2.4 on 2021-01-16 19:06

from django.db import migrations
import phonenumbers


def transfer_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.filter(owners_phonenumber='+70000000000'):
        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(parsed_phone):
            flat.owner_pure_phone = parsed_phone
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210116_2151'),
    ]

    operations = [migrations.RunPython(transfer_phone_numbers),
    ]
