# Generated by Django 2.2.4 on 2021-01-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20210111_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(null=True, verbose_name='Текст жалобы')),
                ('complaint_flat', models.ForeignKey(null=True, on_delete='SET_NULL', to='property.Flat', verbose_name='Квартира, на которую пожаловались')),
            ],
        ),
    ]
