# Generated by Django 2.2.4 on 2021-01-12 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0008_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
