# Generated by Django 2.2.4 on 2021-01-16 20:24

from django.db import migrations


def transfer_owners_from_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner,
                                    owner_pure_phone=flat.owner_pure_phone,
                                    owners_phonenumber=flat.owners_phonenumber)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20210116_2257'),
    ]

    operations = [migrations.RunPython(transfer_owners_from_flats),
    ]
