# Generated by Django 2.2.4 on 2021-01-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_remove_flat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(db_index=True, verbose_name='Новое здание?'),
        ),
    ]
